/**
 * Pure planning logic: diff a catalogue against what is on a watch, and render
 * the fallback install scripts. No DOM and no filesystem, so this is testable
 * in Node and shared with the browser.
 */

import { compareVersions } from './uapp.js';

/** @typedef {{appId:string,folder:string,file:string,version:string,versionPacked:number,size:number,extraUapps:string[]}} Installed */

/**
 * Compare catalogue against installed apps.
 *
 * Keyed on AppID, never on folder or display name: folder names are arbitrary
 * and display names can contain a path separator (GlanceARHR is "AVG / R HR").
 *
 * @returns {{entries: Array, foreign: Installed[]}} `foreign` is anything on the
 *   watch that the catalogue does not know about — reported, never touched.
 */
export function buildPlan(catalog, installed) {
  const byId = new Map(installed.map((i) => [i.appId, i]));
  const entries = catalog.apps.map((app) => {
    const on = byId.get(app.appId);
    if (!on) return { app, status: 'install', installed: null, identicalPayload: false };
    const delta = compareVersions(app.versionPacked, on.versionPacked);
    let status = 'current';
    if (delta > 0) status = 'update';
    else if (delta < 0) status = 'newer-on-watch';
    // Same version but different bytes still warrants a rewrite: a truncated or
    // corrupted install reports the right version in its header.
    else if (on.size !== app.size) status = 'update';

    // Version moved but the code did not. Still offered — installing does change
    // what the watch reports — but the UI says so rather than implying new code.
    // Only known once the installed file has been hashed, which the caller does
    // lazily for update candidates.
    const identicalPayload =
      status === 'update' &&
      Boolean(on.payloadSha256) &&
      Boolean(app.payloadSha256) &&
      on.payloadSha256 === app.payloadSha256;

    return { app, status, installed: on, identicalPayload };
  });

  const known = new Set(catalog.apps.map((a) => a.appId));
  const foreign = installed.filter((i) => !known.has(i.appId));
  return { entries, foreign };
}

/** Entries that would be written, in catalogue order. */
export function actionable(plan) {
  return plan.entries.filter((e) => e.status === 'install' || e.status === 'update');
}

/**
 * Update candidates whose installed bytes have not been hashed yet.
 *
 * Reading a whole .uapp off the watch is far more expensive than reading its
 * 48-byte header, so callers scan headers first and only deepen these.
 */
export function needsPayloadHash(plan) {
  return plan.entries.filter(
    (e) => e.status === 'update' && e.installed && !e.installed.payloadSha256,
  );
}

/** Human-readable reason a job is in the plan. */
export function describeJob(entry) {
  if (entry.status === 'install') return `install ${entry.app.version}`;
  const move = `${entry.installed.version} → ${entry.app.version}`;
  return entry.identicalPayload ? `${move} · version stamp only, identical code` : move;
}

function shQuote(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

function psQuote(s) {
  return `'${String(s).replace(/'/g, `''`)}'`;
}

/**
 * Windows fallback installer.
 *
 * Mirrors the ordering proven by Update-Watch-Apps.ps1 in the UNA SDK:
 * resolve the drive by volume label, copy the new .uapp with [IO.File]::Copy
 * (scripted Copy-Item to this volume has produced silent corruption), verify,
 * and only then delete the stale binary. settings.json and Activity\ are never
 * touched, so app settings and recorded activities survive.
 */
export function powershellScript(plan, { baseUrl, label = 'UNA WATCH' } = {}) {
  const jobs = actionable(plan);
  const lines = [
    '#Requires -Version 5.1',
    '<#',
    '  Generated by Kira. Installs UNA Watch apps over USB mass storage.',
    '  Preserves each app\'s settings.json and Activity\\ data.',
    '  Unofficial; not affiliated with UNA Watch Ltd.',
    '#>',
    'Set-StrictMode -Version 2.0',
    "$ErrorActionPreference = 'Stop'",
    '',
    `$Label   = ${psQuote(label)}`,
    `$BaseUrl = ${psQuote(baseUrl)}`,
    '',
    '# Find the watch by volume label rather than a drive letter, which moves.',
    '$vol = @(Get-Volume | Where-Object { $_.FileSystemLabel -eq $Label -and $_.DriveLetter })',
    "if ($vol.Count -ne 1) { throw \"Expected exactly one volume labelled '$Label', found $($vol.Count). Connect the watch.\" }",
    '$appsRoot = "{0}:\\Apps" -f $vol[0].DriveLetter',
    'if (-not (Test-Path -LiteralPath $appsRoot)) { throw "No Apps folder at $appsRoot." }',
    'Write-Host "Watch apps folder: $appsRoot"',
    '',
    '$tmp = Join-Path ([IO.Path]::GetTempPath()) ("kira-" + [Guid]::NewGuid().ToString("N"))',
    '[IO.Directory]::CreateDirectory($tmp) | Out-Null',
    'try {',
  ];

  for (const entry of jobs) {
    const { app, status } = entry;
    const note = entry.identicalPayload ? `${status}; identical code, version stamp only` : status;
    lines.push(
      '',
      `  # ${app.name} ${app.version} (${note})`,
      `  $folder = ${psQuote(app.folder)}; $file = ${psQuote(app.file)}; $sha = ${psQuote(app.sha256)}`,
      `  $url = "$BaseUrl/${app.download}"`,
      '  $dl = Join-Path $tmp $file',
      '  Write-Host "  downloading $folder/$file"',
      '  Invoke-WebRequest -Uri $url -OutFile $dl -UseBasicParsing',
      '  $got = (Get-FileHash -LiteralPath $dl -Algorithm SHA256).Hash.ToLower()',
      '  if ($got -ne $sha) { throw "$file : SHA-256 mismatch (expected $sha, got $got)" }',
      '  $dir = Join-Path $appsRoot $folder',
      '  [IO.Directory]::CreateDirectory($dir) | Out-Null',
      '  $dst = Join-Path $dir $file',
      '  # .NET copy, not Copy-Item: the latter has silently corrupted this volume.',
      '  [IO.File]::Copy($dl, $dst, $true)',
      '  if ((Get-Item -LiteralPath $dst).Length -ne (Get-Item -LiteralPath $dl).Length) {',
      '    [IO.File]::Delete($dst); throw "$file : size mismatch after copy; stale binary left in place"',
      '  }',
      '  # New binary is good, so it is now safe to drop any older .uapp. The watch',
      '  # loads the FIRST .uapp in the folder, so leaving two can boot the old one.',
      '  Get-ChildItem -LiteralPath $dir -Filter *.uapp -File |',
      '    Where-Object { $_.Name -ne $file } |',
      '    ForEach-Object { [IO.File]::Delete($_.FullName); Write-Host "    removed stale $($_.Name)" }',
      `  Write-Host "  [ok] $folder -> $file"`,
    );
  }

  lines.push(
    '}',
    'finally { Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue }',
    '',
    'Write-Host ""',
    "Write-Host 'NEXT STEPS'",
    "Write-Host '  1. Safely eject the watch (tray -> Safely Remove Hardware).'",
    "Write-Host '  2. Reboot the watch: the launcher list is rebuilt only at boot.'",
    "Write-Host '  3. Reconnect and re-run Kira'\\''s Verify step to check the writes landed in flash.'",
  );
  return `${lines.join('\n')}\n`;
}

/** macOS/Linux fallback installer. Same ordering and guarantees. */
export function shellScript(plan, { baseUrl, mount = '/Volumes/UNA WATCH' } = {}) {
  const jobs = actionable(plan);
  const lines = [
    '#!/bin/sh',
    '# Generated by Kira. Installs UNA Watch apps over USB mass storage.',
    "# Preserves each app's settings.json and Activity/ data.",
    '# Unofficial; not affiliated with UNA Watch Ltd.',
    'set -eu',
    '',
    `MOUNT="\${1:-${mount}}"`,
    `BASE_URL=${shQuote(baseUrl)}`,
    'APPS="$MOUNT/Apps"',
    '[ -d "$APPS" ] || { echo "No Apps folder at $APPS. Pass the mount point as the first argument." >&2; exit 1; }',
    'echo "Watch apps folder: $APPS"',
    '',
    'TMP=$(mktemp -d)',
    'trap \'rm -rf "$TMP"\' EXIT INT TERM',
    '',
    'sha256_of() {',
    '  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d" " -f1',
    '  else sha256sum "$1" | cut -d" " -f1; fi',
    '}',
  ];

  for (const entry of jobs) {
    const { app, status } = entry;
    const note = entry.identicalPayload ? `${status}; identical code, version stamp only` : status;
    lines.push(
      '',
      `# ${app.name} ${app.version} (${note})`,
      `folder=${shQuote(app.folder)}; file=${shQuote(app.file)}; sha=${shQuote(app.sha256)}`,
      `echo "  downloading $folder/$file"`,
      `curl -fsSL "$BASE_URL/${app.download}" -o "$TMP/$file"`,
      'got=$(sha256_of "$TMP/$file")',
      'if [ "$got" != "$sha" ]; then echo "$file: SHA-256 mismatch (expected $sha, got $got)" >&2; exit 1; fi',
      'mkdir -p "$APPS/$folder"',
      'cp "$TMP/$file" "$APPS/$folder/$file"',
      '# New binary is in place, so stale .uapp files can go. The watch loads the',
      '# FIRST .uapp in a folder, so leaving two can boot the old one.',
      'for old in "$APPS/$folder"/*.uapp; do',
      '  [ -e "$old" ] || continue',
      '  case "$(basename "$old")" in "$file") ;; *) rm -f "$old"; echo "    removed stale $(basename "$old")";; esac',
      'done',
      'echo "  [ok] $folder -> $file"',
    );
  }

  lines.push(
    '',
    'sync',
    'echo',
    'echo "NEXT STEPS"',
    'echo "  1. Eject the watch:  diskutil eject \\"$MOUNT\\"   (macOS)  /  udisksctl unmount  (Linux)"',
    'echo "  2. Reboot the watch: the launcher list is rebuilt only at boot."',
    'echo "  3. Reconnect and re-run Kira\'s Verify step to check the writes landed in flash."',
  );
  return `${lines.join('\n')}\n`;
}
